version: '3.8'

services:
  mylibrary-frontend:
    container_name: mylibrary-frontend
    build:
      context: .
      dockerfile: docker/marketplace/dev/Dockerfile
    command: ["ng", "serve", "--port=8080", "--host=0.0.0.0", "-c development-ai4eosc"]
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
    - 9092:8080
  proxy:
    container_name: nginx-proxy
    image: nginx
    environment:
      - MY_PATH_API_AIOD_CATALOGUE=https://aiod-dev.i3a.es
      - MY_PATH_API_MY_LIB=http://172.17.0.1:8090
    command: sh -c "/etc/nginx/script.sh"
    volumes:
      - ./docker/marketplace/script.sh:/etc/nginx/script.sh
      - ./docker/nginx/nginx-proxy.conf:/etc/nginx/nginx.conf.template
    ports:
      - 8083:80
