version: '3.8'

services:
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MY_PATH_API_AIOD_CATALOGUE: ${MY_PATH_API_AIOD_CATALOGUE}
      MY_PATH_API_MY_LIB: ${MY_PATH_API_MY_LIB}
      MY_PATH_MARKETPLACE: ${MY_PATH_MARKETPLACE}
      AIOD_ENHANCED_API: ${AIOD_ENHANCED_API}
    volumes:
      - ./docker/marketplace/script.sh:/etc/nginx/script.sh
      - ./docker/nginx/nginx-proxy-prod.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 9092:80

  mylibrary-nginx-frontend:
    container_name: mylibrary-nginx-frontend
    build:
      context: .
      dockerfile: docker/marketplace/prod/Dockerfile
    env_file:
      - .env
    environment:
      MY_PATH_API_AIOD_CATALOGUE: ${MY_PATH_API_AIOD_CATALOGUE}
      MY_PATH_API_MY_LIB: ${MY_PATH_API_MY_LIB}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      AIOD_ENHANCED_API: ${AIOD_ENHANCED_API}
    ports:
      - 9094:80