version: '3.8'

services:
  nginx-marketplace-frontend:
    container_name: nginx-marketplace-frontend
    build:
      context: .
      dockerfile: docker/marketplace/prod/Dockerfile
    environment:
      - MY_PATH_API_AIOD_CATALOGUE=https://aiod-dev.i3a.es
      - MY_PATH_API_MY_LIB=http://192.168.1.141:9090
    command: sh -c "/etc/nginx/script.sh"
    volumes:
      - ./docker/marketplace/script.sh:/etc/nginx/script.sh
      - ./docker/nginx/nginx-proxy.conf:/etc/nginx/nginx.conf.template
    ports:
      - 9092:80