export const modelConfig = {
  AIModel: {
    columns: [
      'description',
      'same_as',
      'distribution',
      'distribution.dependency',
    ],
    title: 'AI Model',
  },
  Dataset: {
    columns: [
      'description',
      'license',
      'same_as',
      'distribution',
      'distribution.name',
      'distribution.checksum',
      'distribution.description',
      'distribution.checksum_algorithm',
      'distribution.content_url',
      'distribution.encoding_format',
    ],
    title: 'Dataset',
  },
  Experiment: {
    columns: [
      'description',
      'media',
      'media.description',
      'media.checksum',
      'media.checksum_algorithm',
      'media.content_size_kb',
      'media.content_url',
      'media.copyright',
      'media.date_published',
      'license',
      'same_as',
      'distribution',
      'distribution.name',
      'distribution.description',
      'distribution.content_url',
      'distribution.checksum_algorithm',
      'execution_settings',
      'badge',
    ],
    title: 'Experiment',
  },
  'Educational resource': {
    columns: [
      'description',
      'media',
      'media.description',
      'media.name',
      'media.content_url',
      'same_as',
    ],
    title: 'Educational Resource',
  },
  Publication: {
    columns: ['description', 'type'],
    title: 'Publication',
  },
  'Case studies': {
    columns: [
      'description',
      'distribution',
      'distribution.platform',
      'distribution.name',
      'distribution.checksum',
      'distribution.checksum_algorithm',
      'distribution.content_url',
      'distribution.encoding_format',
      'media',
      'media.description',
      'media.checksum',
      'media.checksum_algorithm',
      'media.content_size_kb',
      'media.content_url',
      'media.copyright',
      'media.date_published',
      'same_as',
    ],
    title: 'Case Studies',
  },
};
