export const modelConfig = {
  usuarios: {
    columns: ['nombre', 'email', 'rol'],
    title: 'Usuarios',
  },
  productos: {
    columns: ['nombre', 'precio', 'stock'],
    title: 'Productos',
  },
  pedidos: {
    columns: ['id', 'cliente', 'fecha'],
    title: 'Pedidos',
  },
  educational: {
    columns: [
      // From AssetModel
      'identifier',
      'name',
      'description',
      'platform',
      'platform_resource_identifier',
      'keywords',
      'sameAs',
      'license',
      'research_area',
      'scientific_domain',
      'date_published',
      'distributions',
      'alternateName',
      'media',
      'version',
      'citation',
      'dateCreated',
      // From EducationalResourceModel
      'aiodEntry.platform',
      'aiodEntry.platformIdentifier',
      'aiodEntry.dateModified',
      'aiodEntry.dateCreated',
      'aiodEntry.editor',
      'aiodEntry.status',
      'timeRequired',
      'accessMode',
      'aiResourceIdentifier',
      'applicationArea',
      'contact',
      'content',
      'creator',
      'educationalLevel',
      'hasPart',
      'inLanguage',
      'industrialSector',
      'isPartOf',
      'location',
      'note',
      'pace',
      'prerequisite',
      'relevantLink',
      'relevantResource',
      'relevantTo',
      'targetAudience',
      'type',
    ],
    title: 'Educational Resources',
  },
};
